
name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # se os seus docs precisam de submodules, descomente a linha seguinte
          # submodules: true

      # Configura o Bun e gerencia o cache automaticamente
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Instala as dependências usando o Bun
      - name: Install Deps
        run: bun install

      # Executa o build com o Bun e gera o arquivo .nojekyll
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          bun run docs:build > src/.vuepress/dist/.nojekyll

      # Faz o deploy para o GitHub Pages
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
